/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CanvasRouteImport } from './routes/_canvas'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as CanvasProtectedRouteImport } from './routes/_canvas/_protected'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppProtectedRouteImport } from './routes/_app/_protected'
import { Route as AppProtectedProfileRouteImport } from './routes/_app/_protected/profile'
import { Route as AppProtectedSora2WorkflowIndexRouteImport } from './routes/_app/_protected/sora2-workflow/index'
import { Route as CanvasProtectedSora2WorkflowWorkflowIdRouteImport } from './routes/_canvas/_protected/sora2-workflow/$workflowId'

const CanvasRoute = CanvasRouteImport.update({
  id: '/_canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CanvasProtectedRoute = CanvasProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => CanvasRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedSora2WorkflowIndexRoute =
  AppProtectedSora2WorkflowIndexRouteImport.update({
    id: '/sora2-workflow/',
    path: '/sora2-workflow/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const CanvasProtectedSora2WorkflowWorkflowIdRoute =
  CanvasProtectedSora2WorkflowWorkflowIdRouteImport.update({
    id: '/sora2-workflow/$workflowId',
    path: '/sora2-workflow/$workflowId',
    getParentRoute: () => CanvasProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/profile': typeof AppProtectedProfileRoute
  '/sora2-workflow/$workflowId': typeof CanvasProtectedSora2WorkflowWorkflowIdRoute
  '/sora2-workflow/': typeof AppProtectedSora2WorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/profile': typeof AppProtectedProfileRoute
  '/sora2-workflow/$workflowId': typeof CanvasProtectedSora2WorkflowWorkflowIdRoute
  '/sora2-workflow': typeof AppProtectedSora2WorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_canvas': typeof CanvasRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_canvas/_protected': typeof CanvasProtectedRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_canvas/_protected/sora2-workflow/$workflowId': typeof CanvasProtectedSora2WorkflowWorkflowIdRoute
  '/_app/_protected/sora2-workflow/': typeof AppProtectedSora2WorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/sora2-workflow/$workflowId'
    | '/sora2-workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/sora2-workflow/$workflowId'
    | '/sora2-workflow'
  id:
    | '__root__'
    | '/_app'
    | '/_canvas'
    | '/_app/_protected'
    | '/_app/about'
    | '/_app/login'
    | '/_app/register'
    | '/_canvas/_protected'
    | '/_app/'
    | '/_app/_protected/profile'
    | '/_canvas/_protected/sora2-workflow/$workflowId'
    | '/_app/_protected/sora2-workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CanvasRoute: typeof CanvasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_canvas': {
      id: '/_canvas'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_canvas/_protected': {
      id: '/_canvas/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CanvasProtectedRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/sora2-workflow/': {
      id: '/_app/_protected/sora2-workflow/'
      path: '/sora2-workflow'
      fullPath: '/sora2-workflow/'
      preLoaderRoute: typeof AppProtectedSora2WorkflowIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_canvas/_protected/sora2-workflow/$workflowId': {
      id: '/_canvas/_protected/sora2-workflow/$workflowId'
      path: '/sora2-workflow/$workflowId'
      fullPath: '/sora2-workflow/$workflowId'
      preLoaderRoute: typeof CanvasProtectedSora2WorkflowWorkflowIdRouteImport
      parentRoute: typeof CanvasProtectedRoute
    }
  }
}

interface AppProtectedRouteChildren {
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
  AppProtectedSora2WorkflowIndexRoute: typeof AppProtectedSora2WorkflowIndexRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedProfileRoute: AppProtectedProfileRoute,
  AppProtectedSora2WorkflowIndexRoute: AppProtectedSora2WorkflowIndexRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

interface AppRouteChildren {
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProtectedRoute: AppProtectedRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CanvasProtectedRouteChildren {
  CanvasProtectedSora2WorkflowWorkflowIdRoute: typeof CanvasProtectedSora2WorkflowWorkflowIdRoute
}

const CanvasProtectedRouteChildren: CanvasProtectedRouteChildren = {
  CanvasProtectedSora2WorkflowWorkflowIdRoute:
    CanvasProtectedSora2WorkflowWorkflowIdRoute,
}

const CanvasProtectedRouteWithChildren = CanvasProtectedRoute._addFileChildren(
  CanvasProtectedRouteChildren,
)

interface CanvasRouteChildren {
  CanvasProtectedRoute: typeof CanvasProtectedRouteWithChildren
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasProtectedRoute: CanvasProtectedRouteWithChildren,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CanvasRoute: CanvasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
